package com.defencefirst.siemcentar.model;

public enum Permission {
	PERMISSION_FIND_ALL_CERTIFICATES,
	PERMISSION_GET_RECOMMENDED_VALIDITY_PERIODS,
	PERMISSION_FIND_CERTIFICATE_BY_SERIAL_NUMBER,
	PERMISSION_GET_ALL_CAS_WHICH_ARE_NOT_REVOKED,
	PERMISSION_GET_ALL_CERTIFICATES_AS_TREE_DATA,
	PERMISSION_CREATE_NEW_CERTIFICATE,
	PERMISSION_REVOKE_CERTIFICATE,
	PERMISSION_SEARCH_LOGS,
	PERMISSION_READ_ALARMS,
	PERMISSION_READ_RAISED_ALARMS,
	PERMISSION_WRITE_ALARMS,
	PERMISSION_REPORTS;
}
